Introduce stub file
In an effort to prevent error messages at the end users when he/she does a mypy check:
- trying-things.py:1: error: Skipping analyzing 'splogging.logger': found module but no type hints or library stubs
- trying-things.py:1: error: Skipping analyzing 'splogging': found module but no type hints or library stubs